annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  catalog.cattle.io/display-name: Virtual Clusters
  catalog.cattle.io/ui-extensions-version: '>= 3.0.5-rc.6'
  catalog.cattle.io/rancher-version: '>=2.12.0'
apiVersion: v2
appVersion: 1.0.0
description: Virtual cluster provisioning using K3K (Prime only)
name: virtual-clusters
type: application
version: 1.0.0
icon: https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/icons/virtual-clusters/1.0.0-icon-k3k.svg
