annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/kube-version: '>= v1.16.0-0'
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/rancher-version: '>= 2.7.0-0 < 2.11.0-0'
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  catalog.cattle.io/display-name: NeuVector UI Extension
apiVersion: v2
appVersion: 2.0.1
description: NeuVector extension for Rancher Manager
name: neuvector-ui-ext
type: application
version: 2.0.1
icon: https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/icons/neuvector-ui-ext/2.0.1-nv-icon.svg
