annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  catalog.cattle.io/display-name: Harvester
  catalog.cattle.io/kube-version: '>= 1.16.0-0'
  catalog.cattle.io/rancher-version: '>= 2.13.0-0'
  catalog.cattle.io/ui-extensions-version: '>= 3.0.0 < 4.0.0'
apiVersion: v2
appVersion: 1.7.0
description: Rancher UI Extension for Harvester
name: harvester
type: application
version: 1.7.0
icon: https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/icons/harvester/1.7.0-icon.svg
