annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  catalog.cattle.io/rancher-version: '>= 2.13.0-0'
  catalog.cattle.io/display-name: Alibaba Cloud (ACK) Provisioning
  catalog.cattle.io/ui-extensions-version: '>= 3.0.0 < 4.0.0'
  catalog.cattle.io/prime-only: 'true'
apiVersion: v2
appVersion: 1.0.1
description: Create Alibaba Cloud clusters in Rancher
name: ali
type: application
version: 1.0.1
icon: https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/icons/ali/1.0.1-alibaba.svg
