nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  endpoint: >-
    https://raw.githubusercontent.com/rancher/ali-ui/gh-pages/extensions/ali/1.0.1
  compressedEndpoint: >-
    https://raw.githubusercontent.com/rancher/ali-ui/gh-pages/extensions/ali/1.0.1.tgz
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/rancher-version: ">= 2.13.0-0"
    catalog.cattle.io/display-name: Alibaba Cloud (ACK) Provisioning
    catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
    catalog.cattle.io/certified: rancher
    catalog.cattle.io/prime-only: "true"
