nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  endpoint: >-
    https://raw.githubusercontent.com/rancher/virtual-clusters-ui/gh-pages/extensions/virtual-clusters/1.0.1
  compressedEndpoint: >-
    https://raw.githubusercontent.com/rancher/virtual-clusters-ui/gh-pages/extensions/virtual-clusters/1.0.1.tgz
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/display-name: Virtual Clusters
    catalog.cattle.io/ui-extensions-version: ">= 3.0.5-rc.6"
    catalog.cattle.io/rancher-version: ">=2.12.0"
    catalog.cattle.io/prime-only: "true"
